{ ... }:
{
  home.file."Library/Application Support/Cursor/User/settings.json" = {
    text = ''
      // generated by home-manager
      ${builtins.readFile ./settings.vscode.jsonc}
    '';
    force = true;
  };

  # キーバインディングの設定も管理する場合は以下をアンコメント
  # home.file."Library/Application Support/Cursor/User/keybindings.json" = {
  #   text = ''
  #     // generated by home-manager
  #     ${builtins.readFile ../../../.vscode/keybindings.json}
  #   '';
  #   force = true;
  # };
}
