{ ... }:
{
  home.file."Library/Application Support/Cursor/User/settings.json" = {
    text = ''
      // generated by home-manager
      ${builtins.readFile ./settings.vscode.jsonc}
    '';
    force = true;
  };
  home.file."Library/Application Support/Cursor/User/keybindings.json" = {
    text = ''
      // generated by home-manager
      ${builtins.readFile ./keybindings.vscode.jsonc}
    '';
    force = true;
  };
}
