{ ... }:
{
  home.file."Library/Application Support/Code/User/settings.json" = {
    text = ''
      // generated by home-manager
      ${builtins.readFile ./vscode/settings.vscode.jsonc}
    '';
    force = true;
  };
}
